const routeTitles = {
  '/': 'Login',
  '/dashboard': 'Dashboard',
  '/dashboard/employee': 'Employee Management',
  '/dashboard/add_employee': 'Add Employee',
  '/dashboard/view_employee': 'View Employee',
  '/dashboard/employee/edit': 'Edit Employee',
  '/dashboard/add_court_martial': 'Add Court Martial Record',
  '/dashboard/edit_court_martial': 'Edit Court Martial Record',
  '/dashboard/add_disciplinary_action': 'Add Disciplinary Action',
  '/dashboard/edit_disciplinary_action': 'Edit Disciplinary Action',
  '/dashboard/add_promotion': 'Add Promotion',
  '/dashboard/edit_promotion': 'Edit Promotion',
  '/dashboard/posting': 'Posting Management',
  '/dashboard/add_posting': 'Add Posting',
  '/dashboard/edit_posting': 'Edit Posting',
  '/dashboard/pay': 'Pay & Allowance',
  '/dashboard/qualification': 'Qualification & Training',
  '/dashboard/medical': 'Medical Records',
  '/dashboard/security': 'Security Clearance',
  '/dashboard/add_emp_clearance': 'Add Employee Clearance',
  '/dashboard/edit_emp_clearance': 'Edit Employee Clearance',
  '/dashboard/awards': 'Awards & Achievements',
  '/dashboard/profile': 'Profile',
};

export default routeTitles;