const routeTitles = {
  '/': 'Login',
  '/dashboard': 'Dashboard',
  '/dashboard/employee': 'Employee Management',
  '/dashboard/add_employee': 'Add Employee',
  '/dashboard/view_employee': 'View Employee',
  '/dashboard/employee/edit': 'Edit Employee',
  '/dashboard/add_court_martial': 'Add Court Martial Record',
  '/dashboard/edit_court_martial': 'Edit Court Martial Record',
  '/dashboard/add_disciplinary_action': 'Add Disciplinary Action',
  '/dashboard/edit_disciplinary_action': 'Edit Disciplinary Action',
  '/dashboard/add_promotion': 'Add Promotion',
  '/dashboard/edit_promotion': 'Edit Promotion',
  '/dashboard/add_emp_allowance': 'Add Employee Allowance',
  '/dashboard/edit_emp_allowance': 'Edit Employee Allowance',
  '/dashboard/add_loan': 'Add Personal Loan',
  '/dashboard/edit_loan': 'Edit Personal Loan',
  '/dashboard/add_emp_civil': 'Add Employee Civil Qualification',
  '/dashboard/edit_emp_civil': 'Edit Employee Civil Qualification',
  '/dashboard/add_emp_atc': 'Add Employee Army Training Course',
  '/dashboard/edit_emp_atc': 'Edit Employee Army Training Course',
  '/dashboard/add_emp_lang': 'Add Employee Language Proficiency',
  '/dashboard/edit_emp_lang': 'Edit Employee Language Proficiency',
  '/dashboard/add_emp_comp_skill': 'Add Employee Computer Skill',
  '/dashboard/edit_emp_comp_skill': 'Edit Employee Computer Skill',
  '/dashboard/add_emp_award': 'Add Employee Award',
  '/dashboard/edit_emp_award': 'Edit Employee Award',
  '/dashboard/add_emp_commendation': 'Add Employee Commendation',
  '/dashboard/edit_emp_commendation': 'Edit Employee Commendation',
  '/dashboard/add_emp_fm': 'Add Employee Foreign Mission',
  '/dashboard/edit_emp_fm': 'Edit Employee Foreign Mission',
  '/dashboard/add_emp_sa': 'Add Employee Sporting Achievement',
  '/dashboard/edit_emp_sa': 'Edit Employee Sporting Achievement',
  '/dashboard/add_medical_history': 'Add Medical History',
  '/dashboard/edit_medical_history': 'Edit Medical History',
  '/dashboard/posting': 'Posting Management',
  '/dashboard/add_posting': 'Add Posting',
  '/dashboard/edit_posting': 'Edit Posting',
  '/dashboard/army_rank': 'Ranks',
  '/dashboard/add_rank': 'Add Rank',
  '/dashboard/edit_rank': 'Edit Rank',
  '/dashboard/corp_and_regiment': 'Corps and Regiments',
  '/dashboard/add_corp_and_reg': 'Add Corp and Regiment',
  '/dashboard/edit_corp_and_reg': 'Edit Corp and Regiment',
  '/dashboard/unit': 'Units',
  '/dashboard/add_unit': 'Add Unit',
  '/dashboard/edit_unit': 'Edit Unit',
  '/dashboard/appointment': 'Appointments',
  '/dashboard/add_appointment': 'Add Appointment',
  '/dashboard/edit_appointment': 'Edit Appointment',
  '/dashboard/special_duty': 'Special Duties',
  '/dashboard/add_special_duty': 'Add Special Duty',
  '/dashboard/edit_special_duty': 'Edit Special Duty',
  '/dashboard/overseas_posting': 'Overseas Postings',
  '/dashboard/add_overseas_posting': 'Add Overseas Posting',
  '/dashboard/edit_overseas_posting': 'Edit Overseas Posting',
  '/dashboard/pay': 'Pay & Allowance',
  '/dashboard/qualification': 'Qualification & Training',
  '/dashboard/medical': 'Medical Records',
  '/dashboard/security': 'Security Clearance',
  '/dashboard/security_clearance': 'Security Clearances',
  '/dashboard/add_security_clearance': 'Add Security Clearance',
  '/dashboard/edit_security_clearance': 'Edit Security Clearance',
  '/dashboard/add_emp_clearance': 'Add Employee Clearance',
  '/dashboard/edit_emp_clearance': 'Edit Employee Clearance',
  '/dashboard/awards': 'Awards & Achievements',
  '/dashboard/profile': 'Profile',
};

export default routeTitles;